FROM --platform=linux/amd64 python:3.10.12-slim-bullseye
ENV PYTHONUNBUFFERED=1
RUN apt-get update && \
    apt-get install -y libpq-dev gcc && apt-get install -y ffmpeg && apt-get install -y wget
WORKDIR /django
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
