# Generated by Django 4.2.4 on 2023-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdata_join_epoch_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='userdata',
            name='full_name',
            field=models.TextField(default='system'),
            preserve_default=False,
        ),
    ]
