# Generated by Django 4.2.4 on 2023-09-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_rename_username_userdata_email_userdata_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.UUIDField()),
                ('video_title', models.TextField()),
                ('video_duration', models.IntegerField()),
                ('platform', models.TextField()),
                ('channel_id', models.TextField()),
                ('channel_name', models.TextField()),
                ('video_url', models.TextField()),
                ('local_video_path', models.TextField(default='')),
                ('local_thumbnail_path', models.TextField(default='')),
                ('is_video_processed', models.BooleanField(default=False)),
                ('video_processed_by', models.TextField(verbose_name='Reuv Play')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('video_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videodata')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('is_video_processed', models.BooleanField()),
                ('queue_position', models.IntegerField()),
                ('request_epoch_time', models.IntegerField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
                ('video_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videodata')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessVideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('session_creation_time', models.IntegerField()),
                ('session_end_time', models.IntegerField()),
                ('status', models.TextField()),
                ('progress', models.IntegerField()),
                ('video_id', models.UUIDField()),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
    ]
