# Generated by Django 4.2.4 on 2023-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_videodata_video_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_processed_on',
            field=models.IntegerField(default=0),
        ),
    ]
