# Generated by Django 4.2.4 on 2023-09-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videodata_video_processed_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processvideosession',
            name='video_id',
        ),
        migrations.AddField(
            model_name='processvideosession',
            name='video_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.videodata'),
            preserve_default=False,
        ),
    ]
