# Generated by Django 4.2.4 on 2023-09-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_processvideosession_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedvideo',
            name='request_completed_epoch_time',
            field=models.IntegerField(default=0),
        ),
    ]
