# Generated by Django 4.2.4 on 2023-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_requestedvideo_request_completed_epoch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosegments',
            name='clip_id',
            field=models.UUIDField(default='4197abfd-d31f-4946-8aa0-832d5ff332f2'),
            preserve_default=False,
        ),
    ]
